import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header";
import { AuthProvider } from "@/contexts/AuthContext";
import AuthInitializer from "@/components/auth/AuthInitializer";
import { DataCacheProvider } from "@/contexts/DataCacheContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps,
}: Readonly<{
  children: React.ReactNode;
  pageProps: { [key: string]: any };
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased bg-black text-white`}
      >
        <AuthProvider>
          <DataCacheProvider>
            <AuthInitializer>
              <Header />
              {children}
            </AuthInitializer>
          </DataCacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
